config/routes.rb
KitsuneUdon::Application.routes.draw do
	resources :pages, :only => [:home, :help, :output]
	
	match '/home', :to => 'pages#home'
	get "pages/home"
	root :to => 'pages#home'
	
	match '/help', :to => 'pages#help'
	get "pages/help"
	
	match '/output', :to => 'pages#output'
	get "pages/output"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
		@title = "Home"
	end

	def help
		@title = "Help"
	end

	def output
		if params[:data][:source].empty?
			flash.now[:error] = "Please provide a language file"
			@title = "Home"
			render 'home'
		else
			result = Kotodama::GRAMMAR.parse params[:data][:source]
			if result.parsed?
				@title = "Output"
				@output = []
				if params[:data][:times].empty?
					times = 1
				elsif params[:data][:times].match /\D/
					flash.now[:error] = "Please provide a valid number"
					@title = "Home"
					render 'home'
				else
					times = params[:data][:times].to_i
				end
				times.times { @output << result.result.generate }
			else
				flash.now[:error] = result.error
				@title = "Home"
				render 'home'
			end
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
	def title
		if @title
			"KitsuneUdon | #{@title}"
		else
			"KitsuenUdon"
		end
	end
	
	def lang_source
		if params.key? :data
			params[:data][:source]
		end
	end
	
	def lang_times
		if params.key? :data
			params[:data][:times]
		end
	end
end

app/views/layouts/_footer.html.erb
<footer>
	<nav>
		<ul>
			<li><%= link_to "Home", home_path %></li>
			<li><%= link_to "Help", help_path %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= title %></title>
		<%= render 'layouts/stylesheets' %>
		<%= stylesheet_link_tag 'custom', :media => 'screen' %>
		<%= javascript_include_tag :defaults %>
		<%= csrf_meta_tag %>
	</head>
<body>
	<div class="container">
		<section>
			<% flash.each do |key, value| %>
				<div class="flash <%= key %>"><%= value %></div>
			<% end %>
			<%= yield %>
		</section>
		<%= render 'layouts/footer' %>
	</div>
</body>
</html>

app/views/pages/help.html.erb
<h1>Pages#help</h1>
<p>Find me in app/views/pages/help.html.erb</p>

app/views/pages/home.html.erb
<h1>Kotodama <%= Kotodama::VERSION %></h1>
<%= form_for :data, :url => output_path do |f| %>
	<div class="field">
		<%= f.label "Language file" %><br />
		<%= f.text_area :source, :value => lang_source %>
	</div>
	<div class="field">
		<%= f.label "Words to generate" %><br />
		<%= f.text_field :times, :value => lang_times %>
	</div>
	<div class="actions">
		<%= f.submit "Generate" %>
	</div>
<% end %>

app/views/pages/output.html.erb
<% @output.each do |word| %>
<%= word %><br />
<% end %>